# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  CI_USER: ${{ secrets.CI_USER}}
  CI_EMAIL: ${{ secrets.CI_EMAIL }}
  VERSION: ${{ github.event.inputs.version }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Run lint
        run: npm run lint --if-present
      - name: Completed Lint
        run: echo "HOORRAAYYY!!"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Run Build
        run: npm run build --if-present
      - name: Completed Build
        run: echo "HOORRAAYYY!!"
  release:
    needs: [lint, build]
    runs-on: ubuntu-latest 
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - run: git config --global user.email "$CI_EMAIL"
      - run: git config --global user.name "$CI_USER"
      - name: NPM version
        run: npm version $VERSION -m 'chore(release) version %s'

      - name: NPM publish
        run: npm publish --access public

      - name: Changelog
        uses: yashanand1910/standard-release-notes@v1.2.1
        id: get_release_notes
        with:
          version: ${{ github.event.inputs.version }} # Required

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.get_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false

      - name: Update Changelog
        run: echo "$BODY" | cat - ./CHANGELOG.md > /tmp/out && mv /tmp/out ./CHANGELOG.md
        env:
          BODY:  ${{ steps.get_release_notes.outputs.release_notes }}
      - run: git add -A
      - run: git commit -m "chore(changelog) updating change log $VERSION"
        env:
          VERSION:  ${{ github.event.inputs.version }}
      - name: Push Release
        run: git push

